resources:
  - name: sources
    type: git
    source:
      uri: https://github.com/joris77/admin-web.git
      branch: master
  - name: admin-web-image
    type: docker-image
    source:
      repository: smartworkx/admin-web
      email: {{docker_mail}}
      username: {{docker_user}}
      password: {{docker_pass}}

jobs:
- name: test
  plan:
  - get: sources
    trigger: true
  - task: lint
    file: sources/pipeline/lint.yml
- name: build
  plan:
  - get: sources
    trigger: true
  - task: dist
    file: sources/pipeline/dist.yml
  - put: admin-web-image
    params: {build: sources}
- name: deploy-staging
  plan:
  - get: admin-web-image
    trigger: false
  - task: deploy
    file: sources/pipeline/deploy.yml
