resources:
  - name: sources
    type: git
    source:
      uri: https://github.com/joris77/admin-web.git
      branch: master

jobs:
- name: test
  plan:
  - get: sources
    trigger: true
  - task: test
    file: sources/pipeline/test.yml
  - task: lint
    file: sources/pipeline/lint.yml
  - task: dist
    file: sources/pipeline/dist.yml
